services:
  myapp:
    build:
      dockerfile: Dockerfile
      context: ./client
    container_name: myapp_frontend_container
    hostname: myapp_frontend_host
    env_file:
      - ./client/.env
    ports:
      - '3010:5173'
    restart: always

networks:
  default:
    name: nginx_rp_tier
    external: true
